import { Router } from 'express';                                                                                                                                                                          
import { PrivateNoteController } from '../../controllers/private-note.controller';                                                                                                                         
import { authenticateJWT } from '../../middlewares/auth.middleware';                                                                                                                                       
import { verifyPrivateSession } from '../../middlewares/private-pin.middleware';                                                                                                                           
import { rateLimiter } from '../../middlewares/rate-limiter.middleware';                                                                                                                                   
                                                                                                                                                                                                            
const router = Router();                                                                                                                                                                                   
                                                                                                                                                                                                            
// Verify PIN (Cần JWT + Rate Limit 5 req/min)                                                                                                                                                          
router.post('/private/verify-pin', authenticateJWT, rateLimiter(5, 60), PrivateNoteController.verifyPin);                                                                                                  
                                                                                                                                                                                                            
// Các API Private Notes (Bắt buộc cần cả JWT lẫn X-Private-Token)                                                                                                                                      
router.get('/private/notes', authenticateJWT, verifyPrivateSession, PrivateNoteController.getPrivateNotes);                                                                                                
router.post('/private/notes', authenticateJWT, verifyPrivateSession, PrivateNoteController.createPrivateNote);                                                                                             
router.delete('/private/notes/:id', authenticateJWT, verifyPrivateSession, PrivateNoteController.deletePrivateNote);                                                                                       
                                                                                                                                                                                                            
export default router; 