import { Router } from 'express';                                                                                                                                                                          
import { TopicController } from '../../controllers/topic.controller';                                                                                                                                      
import { authenticateJWT } from '../../middlewares/auth.middleware';                                                                                                                                       
                                                                                                                                                                                                            
const router = Router();                                                                                                                                                                                   
                                                                                                                                                                                                            
router.use(authenticateJWT); // Bắt buộc đăng nhập cho toàn bộ API Topic                                                                                                                                   
                                                                                                                                                                                                            
router.get('/topics', TopicController.getTopics);                                                                                                                                                          
router.post('/topics', TopicController.createTopic);                                                                                                                                                       
router.delete('/topics/:id', TopicController.deleteTopic);                                                                                                                                                 
                                                                                                                                                                                                            
export default router;