import { Response, NextFunction } from 'express';                                                                                                                                                          
import { redisClient } from '../config/redis';                                                                                                                                                             
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from './auth.middleware';                                                                                                                                                  
                                                                                                                                                                                                            
export const verifyPrivateSession = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {                                                                                              
    const privateToken = req.headers['x-private-token'] as string;                                                                                                                                           
    const userId = req.user?.userId;                                                                                                                                                                         
                                                                                                                                                                                                            
    if (!privateToken) {                                                                                                                                                                                     
        return ApiResponse.error(res, 403, 'FORBIDDEN', 'Yêu cầu Header X-Private-Token để truy cập vùng Riêng tư');                                                                                           
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    try {                                                                                                                                                                                                    
        // Check Token trong Redis xem có hợp lệ và thuộc về User này không                                                                                                                                    
        const storedUserId = await redisClient.get(`private_session:${privateToken}`);                                                                                                                         
                                                                                                                                                                                                            
        if (!storedUserId || storedUserId !== userId) {                                                                                                                                                        
            return ApiResponse.error(                                                                                                                                                                            
            res,                                                                                                                                                                                               
            403,                                                                                                                                                                                               
            'FORBIDDEN',                                                                                                                                                                                       
            'Phiên truy cập Riêng tư đã hết hạn hoặc không hợp lệ. Vui lòng nhập lại PIN!'                                                                                                                     
            );                                                                                                                                                                                                   
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        next(); // Cho phép đi tiếp                                                                                                                                                                            
    } catch (error: any) {                                                                                                                                                                                   
        return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                            
    }                                                                                                                                                                                                        
};