import { Request, Response } from 'express';                                                                                                                                                               
import jwt from 'jsonwebtoken';                                                                                                                                                                            
import { dbPool } from '../config/database';                                                                                                                                                               
import { config } from '../config/env';                                                                                                                                                                    
import { CryptoService } from '../services/crypto.service';                                                                                                                                                
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from '../middlewares/auth.middleware';                                                                                                                                     
                                                                                                                                                                                                            
export class AuthController {                                                                                                                                                                              
    // Đăng ký tài khoản mới (POST /api/v1/auth/register)                                                                                                                                                 
    static async register(req: Request, res: Response) {                                                                                                                                                     
        const { username, email, password, displayName } = req.body;                                                                                                                                           
                                                                                                                                                                                                            
        if (!username || !email || !password || !displayName) {                                                                                                                                                
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Thiếu thông tin bắt buộc (username, email, password, displayName)');                                                                              
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            // Check trùng email/username                                                                                                                                                                        
            const checkUser = await dbPool.query(
                'SELECT id FROM users WHERE username = $1 OR email = $2',
                [username, email]
            );                                                                                                                                                                                                   
                                                                                                                                                                                                            
            if (checkUser.rows.length > 0) {                                                                                                                                                                     
                return ApiResponse.error(res, 409, 'CONFLICT', 'Username hoặc Email đã được sử dụng');                                                                                                             
            }                                                                                                                                                                                                       
                                                                                                                                                                                                            
            // Hash mật khẩu bằng Argon2id                                                                                                                                                                       
            const passwordHash = await CryptoService.hashData(password);                                                                                                                                         
                                                                                                                                                                                                                
            // Bắt đầu Transaction tạo User + Profile                                                                                                                                                            
            const client = await dbPool.connect();                                                                                                                                                               
            try {                                                                                                                                                                                                
                await client.query('BEGIN');                                                                                                                                                                       
                                                                                                                                                                                                                
                // Insert User                                                                                                                                                                                     
                const userRes = await client.query(                                                                                                                                                                
                    'INSERT INTO users (username, email, password_hash) VALUES ($1, $2, $3) RETURNING id, username, email',                                                                                          
                    [username, email, passwordHash]                                                                                                                                                                  
                );                                                                                                                                                                                                 
                const newUser = userRes.rows[0];                                                                                                                                                                   
                                                                                                                                                                                                            
                // Insert Profile mặc định                                                                                                                                                                         
                await client.query(                                                                                                                                                                                
                    'INSERT INTO profiles (user_id, display_name) VALUES ($1, $2)',                                                                                                                                  
                    [newUser.id, displayName]                                                                                                                                                                        
                );                                                                                                                                                                                                 
                                                                                                                                                                                                            
                await client.query('COMMIT');                                                                                                                                                                      
                                                                                                                                                                                                            
                // Sinh JWT Token                                                                                                                                                                                  
                const token = jwt.sign(                                                                                                                                                                            
                    { userId: newUser.id, username: newUser.username },                                                                                                                                              
                    config.SECURITY.JWT_SECRET,                                                                                                                                                                      
                    { expiresIn: config.SECURITY.JWT_EXPIRES_IN as any }                                                                                                                                             
                );                                                                                                                                                                                                 
                                                                                                                                                                                                            
                return ApiResponse.success(res, 201, 'Đăng ký tài khoản thành công', {                                                                                                                             
                    user: newUser,                                                                                                                                                                                   
                    accessToken: token,                                                                                                                                                                              
                });                                                                                                                                                                                                
            } catch (err) {                                                                                                                                                                                      
                await client.query('ROLLBACK');                                                                                                                                                                    
                throw err;                                                                                                                                                                                         
            } finally {                                                                                                                                                                                          
                client.release();                                                                                                                                                                                  
            }                                                                                                                                                                                                    
        }catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Đăng nhập (POST /api/v1/auth/login)                                                                                                                                                                
    static async login(req: Request, res: Response) {                                                                                                                                                        
        const { username, password } = req.body;                                                                                                                                                               
                                                                                                                                                                                                            
        if (!username || !password) {                                                                                                                                                                          
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Vui lòng nhập username và password');                                                                                                             
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                'SELECT id, username, password_hash FROM users WHERE username = $1',                                                                                                                               
                [username]                                                                                                                                                                                         
            );                                                                                                                                                                                                   
                                                                                                                                                                                                            
            if (result.rows.length === 0) {                                                                                                                                                                      
                return ApiResponse.error(res, 401, 'UNAUTHORIZED', 'Username hoặc mật khẩu không chính xác');                                                                                                      
            }                                                                                                                                                                                                    
                                                                                                                                                                                                            
            const user = result.rows[0];                                                                                                                                                                         
            const isValidPassword = await CryptoService.verifyHash(user.password_hash, password);                                                                                                                
                                                                                                                                                                                                            
            if (!isValidPassword) {                                                                                                                                                                              
                return ApiResponse.error(res, 401, 'UNAUTHORIZED', 'Username hoặc mật khẩu không chính xác');                                                                                                      
            }                                                                                                                                                                                                    
                                                                                                                                                                                                            
            // Sinh JWT Token                                                                                                                                                                                    
            const token = jwt.sign(                                                                                                                                                                              
                { userId: user.id, username: user.username },                                                                                                                                                      
                config.SECURITY.JWT_SECRET,                                                                                                                                                                        
                { expiresIn: config.SECURITY.JWT_EXPIRES_IN as any }                                                                                                                                               
            );                                                                                                                                                                                                   
                                                                                                                                                                                                            
            return ApiResponse.success(res, 200, 'Đăng nhập thành công', {                                                                                                                                       
                user: { id: user.id, username: user.username },                                                                                                                                                    
                accessToken: token,                                                                                                                                                                                
            });                                                                                                                                                                                                  
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Lấy thông tin Profile (GET /api/v1/profile)                                                                                                                                                        
    static async getProfile(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const userId = req.user?.userId;                                                                                                                                                                       
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
            `SELECT u.id, u.username, u.email, p.display_name, p.theme,                                                                                                                                        
                    (p.private_pin_hash IS NOT NULL) AS has_private_pin                                                                                                                                        
            FROM users u                                                                                                                                                                                      
            JOIN profiles p ON u.id = p.user_id                                                                                                                                                               
            WHERE u.id = $1`,                                                                                                                                                                                 
            [userId]                                                                                                                                                                                           
        );                                                                                                                                                                                                   
                                                                                                                                                                                                            
        if (result.rows.length === 0) {                                                                                                                                                                      
            return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy người dùng');                                                                                                                      
        }                                                                                                                                                                                                    
                                                                                                                                                                                                            
        return ApiResponse.success(res, 200, 'Lấy thông tin Profile thành công', result.rows[0]);                                                                                                            
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Đặt / Đổi Private PIN (POST /api/v1/profile/private-pin)                                                                                                                                           
    static async setPrivatePin(req: AuthenticatedRequest, res: Response) {                                                                                                                                   
        const userId = req.user?.userId;                                                                                                                                                                       
        const { newPin } = req.body;                                                                                                                                                                           
                                                                                                                                                                                                            
        if (!newPin || newPin.length !== 6 || !/^\d+$/.test(newPin)) {                                                                                                                                         
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Mã PIN bắt buộc phải gồm đúng 6 chữ số');                                                                                                         
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const pinHash = await CryptoService.hashData(newPin);                                                                                                                                                
                                                                                                                                                                                                            
            await dbPool.query(                                                                                                                                                                                  
                'UPDATE profiles SET private_pin_hash = $1, updated_at = CURRENT_TIMESTAMP WHERE user_id = $2',                                                                                                    
                [pinHash, userId]                                                                                                                                                                                  
            );                                                                                                                                                                                                   
                                                                                                                                                                                                            
            return ApiResponse.success(res, 200, 'Cài đặt mã PIN tab Riêng tư thành công');                                                                                                                      
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
}