import { Response } from 'express';                                                                                                                                                                        
import crypto from 'crypto';                                                                                                                                                                               
import { dbPool } from '../config/database';                                                                                                                                                               
import { redisClient } from '../config/redis';                                                                                                                                                             
import { CryptoService } from '../services/crypto.service';                                                                                                                                                
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from '../middlewares/auth.middleware';                                                                                                                                     
                                                                                                                                                                                                            
export class PrivateNoteController {                                                                                                                                                                       
    // Xác thực PIN tab Riêng tư -> Cấp Session Token (POST /api/v1/private/verify-pin)                                                                                                                   
    static async verifyPin(req: AuthenticatedRequest, res: Response) {                                                                                                                                       
        const userId = req.user?.userId;                                                                                                                                                                       
        const { pin } = req.body;                                                                                                                                                                              
                                                                                                                                                                                                            
        if (!pin) {                                                                                                                                                                                            
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Vui lòng nhập mã PIN 6 chữ số');                                                                                                                  
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            // Lấy Hash PIN từ Profile                                                                                                                                                                           
            const result = await dbPool.query(                                                                                                                                                                   
                'SELECT private_pin_hash FROM profiles WHERE user_id = $1',                                                                                                                                        
                [userId]                                                                                                                                                                                           
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            const pinHash = result.rows[0]?.private_pin_hash;                                                                                                                                                    
                                                                                                                                                                                                                
            if (!pinHash) {                                                                                                                                                                                      
                return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Mày chưa đặt mã PIN tab Riêng tư. Hãy vào Cài đặt để tạo!');                                                                                    
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            // Verify PIN với Hash Argon2id                                                                                                                                                                      
            const isValid = await CryptoService.verifyHash(pinHash, pin);                                                                                                                                        
                                                                                                                                                                                                                
            if (!isValid) {                                                                                                                                                                                      
                return ApiResponse.error(res, 403, 'FORBIDDEN', 'Mã PIN không chính xác!');                                                                                                                        
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            // Sinh Private Session Token sống trong 15 phút (900 giây)                                                                                                                                          
            const sessionToken = crypto.randomBytes(32).toString('hex');                                                                                                                                         
            const TTL_SECONDS = 900; // 15 phút                                                                                                                                                                  
                                                                                                                                                                                                                
            await redisClient.setEx(`private_session:${sessionToken}`, TTL_SECONDS, userId!);                                                                                                                    
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Xác thực PIN thành công', {                                                                                                                                    
                privateSessionToken: sessionToken,                                                                                                                                                                 
                expiresInSeconds: TTL_SECONDS,                                                                                                                                                                     
            });                                                                                                                                                                                                  
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Lấy danh sách & Giải mã Ghi chú riêng tư (GET /api/v1/private/notes)                                                                                                                               
    static async getPrivateNotes(req: AuthenticatedRequest, res: Response) {                                                                                                                                 
        const userId = req.user?.userId;                                                                                                                                                                       
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                `SELECT id, title, encrypted_content, iv, auth_tag, is_pinned, created_at, updated_at                                                                                                              
                FROM private_notes                                                                                                                                                                                
                WHERE user_id = $1                                                                                                                                                                                
                ORDER BY is_pinned DESC, created_at DESC`,                                                                                                                                                        
                [userId]                                                                                                                                                                                           
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            // Giải mã AES-256-GCM cho từng ghi chú trước khi trả về Client                                                                                                                                      
            const decryptedNotes = result.rows.map((note) => {                                                                                                                                                   
                try {                                                                                                                                                                                              
                    const plainContent = CryptoService.decryptText(note.encrypted_content, note.iv, note.auth_tag);                                                                                                  
                    return {                                                                                                                                                                                         
                        id: note.id,                                                                                                                                                                                   
                        title: note.title,                                                                                                                                                                             
                        content: plainContent, // Đã giải mã thành plain text                                                                                                                                          
                        isPinned: note.is_pinned,                                                                                                                                                                      
                        createdAt: note.created_at,                                                                                                                                                                    
                        updatedAt: note.updated_at,                                                                                                                                                                    
                    };                                                                                                                                                                                               
                } catch (decryptErr) {                                                                                                                                                                             
                    return {                                                                                                                                                                                         
                        id: note.id,                                                                                                                                                                                   
                        title: note.title,                                                                                                                                                                             
                        content: '[LỖI GIẢI MÃ: Dữ liệu bị chỉnh sửa trái phép!]',                                                                                                                                     
                        isPinned: note.is_pinned,                                                                                                                                                                      
                        createdAt: note.created_at,                                                                                                                                                                    
                    };                                                                                                                                                                                               
                }                                                                                                                                                                                                  
            });                                                                                                                                                                                                  
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Lấy danh sách ghi chú riêng tư thành công', decryptedNotes);                                                                                                   
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Tạo Ghi chú riêng tư mới -> Mã hóa AES-256-GCM (POST /api/v1/private/notes)                                                                                                                        
    static async createPrivateNote(req: AuthenticatedRequest, res: Response) {                                                                                                                               
        const userId = req.user?.userId;                                                                                                                                                                       
        const { title, content, isPinned = false } = req.body;                                                                                                                                                 
                                                                                                                                                                                                            
        if (!title || !content) {                                                                                                                                                                              
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Tiêu đề và nội dung là bắt buộc');                                                                                                                
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            // Mã hóa nội dung bằng AES-256-GCM                                                                                                                                                                  
            const encrypted = CryptoService.encryptText(content);                                                                                                                                                
                                                                                                                                                                                                                
            const result = await dbPool.query(                                                                                                                                                                   
                `INSERT INTO private_notes (user_id, title, encrypted_content, iv, auth_tag, is_pinned)                                                                                                            
                VALUES ($1, $2, $3, $4, $5, $6)                                                                                                                                                                   
                RETURNING id, title, is_pinned, created_at`,                                                                                                                                                      
                [userId, title, encrypted.encryptedContent, encrypted.iv, encrypted.authTag, isPinned]                                                                                                             
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            return ApiResponse.success(res, 201, 'Tạo ghi chú riêng tư thành công (Đã mã hóa bảo vệ)', result.rows[0]);                                                                                          
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Xóa Ghi chú riêng tư (DELETE /api/v1/private/notes/:id)                                                                                                                                            
    static async deletePrivateNote(req: AuthenticatedRequest, res: Response) {                                                                                                                               
        const userId = req.user?.userId;                                                                                                                                                                       
        const { id } = req.params;                                                                                                                                                                             
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                'DELETE FROM private_notes WHERE id = $1 AND user_id = $2 RETURNING id',                                                                                                                           
                [id, userId]                                                                                                                                                                                       
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            if (result.rows.length === 0) {                                                                                                                                                                      
                return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy ghi chú riêng tư');                                                                                                                
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Xóa ghi chú riêng tư thành công');                                                                                                                             
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
}