import { Response } from 'express';                                                                                                                                                                        
import { dbPool } from '../config/database';                                                                                                                                                               
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from '../middlewares/auth.middleware';                                                                                                                                     
                                                                                                                                                                                                            
export class TopicController {                                                                                                                                                                             
    // Lấy danh sách Chủ đề của User (GET /api/v1/topics)                                                                                                                                                 
    static async getTopics(req: AuthenticatedRequest, res: Response) {                                                                                                                                       
        const userId = req.user?.userId;                                                                                                                                                                       
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                `SELECT id, name, slug, color, created_at, updated_at                                                                                                                                              
                FROM topics                                                                                                                                                                                       
                WHERE user_id = $1                                                                                                                                                                                
                ORDER BY name ASC`,                                                                                                                                                                               
                [userId]                                                                                                                                                                                           
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Lấy danh sách chủ đề thành công', result.rows);                                                                                                                
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Tạo Chủ đề mới (POST /api/v1/topics)                                                                                                                                                               
    static async createTopic(req: AuthenticatedRequest, res: Response) {                                                                                                                                     
        const userId = req.user?.userId;                                                                                                                                                                       
        const { name, color } = req.body;                                                                                                                                                                      
                                                                                                                                                                                                                
        if (!name) {                                                                                                                                                                                           
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Tên chủ đề không được để rỗng');                                                                                                                  
        }                                                                                                                                                                                                      
                                                                                                                                                                                                                
        // Tự sinh slug từ name                                                                                                                                                                                
        const slug = name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');                                                                                                           
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                `INSERT INTO topics (user_id, name, slug, color)                                                                                                                                                   
                VALUES ($1, $2, $3, $4)                                                                                                                                                                           
                RETURNING id, name, slug, color, created_at`,                                                                                                                                                     
                [userId, name, slug, color || '#000000']                                                                                                                                                           
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            return ApiResponse.success(res, 201, 'Tạo chủ đề thành công', result.rows[0]);                                                                                                                       
        } catch (error: any) {                                                                                                                                                                                 
            if (error.code === '23505') { // Postgres Unique Constraint Violation                                                                                                                                
                return ApiResponse.error(res, 409, 'CONFLICT', 'Chủ đề này đã tồn tại');                                                                                                                           
            }                                                                                                                                                                                                    
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Xóa Chủ đề (DELETE /api/v1/topics/:id)                                                                                                                                                             
    static async deleteTopic(req: AuthenticatedRequest, res: Response) {                                                                                                                                     
        const userId = req.user?.userId;                                                                                                                                                                       
        const { id } = req.params;                                                                                                                                                                             
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                'DELETE FROM topics WHERE id = $1 AND user_id = $2 RETURNING id',                                                                                                                                  
                [id, userId]                                                                                                                                                                                       
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            if (result.rows.length === 0) {                                                                                                                                                                      
                return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy chủ đề hoặc không có quyền xóa');                                                                                                  
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Xóa chủ đề thành công');                                                                                                                                       
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
}