import { Response } from 'express';                                                                                                                                                                        
import crypto from 'crypto';                                                                                                                                                                               
import { FileStorageService } from '../services/file-storage.service';                                                                                                                                     
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from '../middlewares/auth.middleware';                                                                                                                                     

export class NoteController {                                                                                                                                                                              
    // Lấy danh sách Ghi chú từ file JSON (GET /api/v1/notes)                                                                                                                                             
    static async getNotes(req: AuthenticatedRequest, res: Response) {                                                                                                                                        
        const { topicId, search } = req.query;                                                                                                                                                                 
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            let notes = await FileStorageService.readJson<any[]>('notes.json', []);                                                                                                                              
                                                                                                                                                                                                                
            // Filter theo topicId nếu có                                                                                                                                                                        
            if (topicId) {                                                                                                                                                                                       
                notes = notes.filter((n) => n.topicId === topicId);                                                                                                                                                
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            // Filter theo từ khóa search nếu có                                                                                                                                                                 
            if (search) {                                                                                                                                                                                        
                const keyword = (search as string).toLowerCase();                                                                                                                                                  
                notes = notes.filter(                                                                                                                                                                              
                    (n) => n.title.toLowerCase().includes(keyword) || n.content.toLowerCase().includes(keyword)                                                                                                      
                );                                                                                                                                                                                                 
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            // Sắp xếp ghim lên đầu                                                                                                                                                                              
            notes.sort((a, b) => (b.isPinned ? 1 : 0) - (a.isPinned ? 1 : 0));                                                                                                                                   
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Lấy danh sách ghi chú thành công (JSON Local)', notes);                                                                                                        
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Tạo Ghi chú mới lưu vào file JSON (POST /api/v1/notes)                                                                                                                                             
    static async createNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const { topicId, title, content, isPinned = false } = req.body;                                                                                                                                        
                                                                                                                                                                                                                
        if (!title || !content) {                                                                                                                                                                              
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Tiêu đề và nội dung là bắt buộc');                                                                                                                
        }                                                                                                                                                                                                      
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const notes = await FileStorageService.readJson<any[]>('notes.json', []);                                                                                                                            
                                                                                                                                                                                                                
            const newNote = {                                                                                                                                                                                    
                id: crypto.randomUUID(),                                                                                                                                                                           
                topicId: topicId || null,                                                                                                                                                                          
                title,                                                                                                                                                                                             
                content,                                                                                                                                                                                           
                isPinned,                                                                                                                                                                                          
                version: 1,                                                                                                                                                                                        
                createdAt: new Date().toISOString(),                                                                                                                                                               
                updatedAt: new Date().toISOString(),                                                                                                                                                               
            };                                                                                                                                                                                                   
                                                                                                                                                                                                                
            notes.unshift(newNote); // Thêm lên đầu danh sách                                                                                                                                                    
            await FileStorageService.writeJson('notes.json', notes);                                                                                                                                             
                                                                                                                                                                                                                
            return ApiResponse.success(res, 201, 'Tạo ghi chú thành công (Đã ghi vào file JSON)', newNote);                                                                                                      
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Xóa Ghi chú khỏi file JSON (DELETE /api/v1/notes/:id)                                                                                                                                              
    static async deleteNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const { id } = req.params;                                                                                                                                                                             
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            let notes = await FileStorageService.readJson<any[]>('notes.json', []);                                                                                                                              
            const initialLength = notes.length;                                                                                                                                                                  
                                                                                                                                                                                                                
            notes = notes.filter((n) => n.id !== id);                                                                                                                                                            
                                                                                                                                                                                                                
            if (notes.length === initialLength) {                                                                                                                                                                
                return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy ghi chú');                                                                                                                         
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            await FileStorageService.writeJson('notes.json', notes);                                                                                                                                             
            return ApiResponse.success(res, 200, 'Xóa ghi chú thành công khỏi file JSON');                                                                                                                       
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }  
    
    // Cập nhật Ghi chú trong file JSON (PUT /api/v1/notes/:id)                                                                                                                                           
    static async updateNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const { id } = req.params;                                                                                                                                                                             
        const { topicId, title, content, isPinned } = req.body;                                                                                                                                                
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const notes = await FileStorageService.readJson<any[]>('notes.json', []);                                                                                                                            
            const index = notes.findIndex((n) => n.id === id);                                                                                                                                                   
                                                                                                                                                                                                                
            if (index === -1) {                                                                                                                                                                                  
                return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy ghi chú để cập nhật');                                                                                                             
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            // Cập nhật thông tin và tăng version                                                                                                                                                                
            notes[index] = {                                                                                                                                                                                     
                ...notes[index],                                                                                                                                                                                   
                topicId: topicId !== undefined ? topicId : notes[index].topicId,                                                                                                                                   
                title: title !== undefined ? title : notes[index].title,                                                                                                                                           
                content: content !== undefined ? content : notes[index].content,                                                                                                                                   
                isPinned: isPinned !== undefined ? isPinned : notes[index].isPinned,                                                                                                                               
                version: (notes[index].version || 1) + 1,                                                                                                                                                          
                updatedAt: new Date().toISOString(),                                                                                                                                                               
            };                                                                                                                                                                                                   
                                                                                                                                                                                                                
            await FileStorageService.writeJson('notes.json', notes);                                                                                                                                             
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Cập nhật ghi chú thành công (JSON Local)', notes[index]);                                                                                                      
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }
}