import { Response } from 'express';                                                                                                                                                                        
import { dbPool } from '../config/database';                                                                                                                                                               
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
import { AuthenticatedRequest } from '../middlewares/auth.middleware';                                                                                                                                     
                                                                                                                                                                                                            
export class NoteController {                                                                                                                                                                              
    // Danh sách Ghi chú thường + Phân trang + Tìm kiếm (GET /api/v1/notes)                                                                                                                               
    static async getNotes(req: AuthenticatedRequest, res: Response) {                                                                                                                                        
        const userId = req.user?.userId;                                                                                                                                                                       
        const { topicId, search, page = '1', limit = '10' } = req.query;                                                                                                                                       
                                                                                                                                                                                                            
        const pageNum = Math.max(1, parseInt(page as string, 10));                                                                                                                                             
        const limitNum = Math.max(1, Math.min(100, parseInt(limit as string, 10)));                                                                                                                            
        const offset = (pageNum - 1) * limitNum;                                                                                                                                                               
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            let queryText = `                                                                                                                                                                                    
                SELECT n.id, n.topic_id, t.name AS topic_name, n.title, n.content, n.is_pinned, n.version, n.created_at, n.updated_at                                                                              
                FROM notes n                                                                                                                                                                                       
                LEFT JOIN topics t ON n.topic_id = t.id                                                                                                                                                            
                WHERE n.user_id = $1                                                                                                                                                                               
            `;                                                                                                                                                                                                   
            const queryParams: any[] = [userId];                                                                                                                                                                 
            let paramCount = 1;                                                                                                                                                                                  
                                                                                                                                                                                                                
            // Filter theo Topic                                                                                                                                                                                 
            if (topicId) {                                                                                                                                                                                       
                paramCount++;                                                                                                                                                                                      
                queryText += ` AND n.topic_id = $${paramCount}`;                                                                                                                                                   
                queryParams.push(topicId);                                                                                                                                                                         
            }                                                                                                                                                                                                    
                                                                                                                                                                                                            
            // Filter theo từ khóa Tìm kiếm (Full-text search)                                                                                                                                                   
            if (search) {                                                                                                                                                                                        
                paramCount++;                                                                                                                                                                                      
                queryText += ` AND (n.title ILIKE $${paramCount} OR n.content ILIKE $${paramCount})`;                                                                                                              
                queryParams.push(`%${search}%`);                                                                                                                                                                   
            }                                                                                                                                                                                                    
                                                                                                                                                                                                            
            // Sắp xếp: Ghim lên đầu trước, sau đó mới đến ngày tạo mới nhất                                                                                                                                     
            queryText += ` ORDER BY n.is_pinned DESC, n.created_at DESC LIMIT $${paramCount + 1} OFFSET $${paramCount + 2}`;                                                                                     
            queryParams.push(limitNum, offset);                                                                                                                                                                  
                                                                                                                                                                                                            
            const result = await dbPool.query(queryText, queryParams);                                                                                                                                           
                                                                                                                                                                                                            
            // Đếm tổng số bản ghi để làm phân trang                                                                                                                                                             
            const countRes = await dbPool.query('SELECT COUNT(*) FROM notes WHERE user_id = $1', [userId]);                                                                                                      
            const totalItems = parseInt(countRes.rows[0].count, 10);                                                                                                                                             
                                                                                                                                                                                                            
            return ApiResponse.success(res, 200, 'Lấy danh sách ghi chú thành công', result.rows, {                                                                                                              
                page: pageNum,                                                                                                                                                                                     
                limit: limitNum,                                                                                                                                                                                   
                totalItems,                                                                                                                                                                                        
                totalPages: Math.ceil(totalItems / limitNum),                                                                                                                                                      
            });                                                                                                                                                                                                  
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Tạo Ghi chú thường mới (POST /api/v1/notes)                                                                                                                                                        
    static async createNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const userId = req.user?.userId;                                                                                                                                                                       
        const { topicId, title, content, isPinned = false } = req.body;                                                                                                                                        
                                                                                                                                                                                                            
        if (!title || !content) {                                                                                                                                                                              
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Tiêu đề và nội dung ghi chú là bắt buộc');                                                                                                        
        }                                                                                                                                                                                                      
                                                                                                                                                                                                            
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
            `INSERT INTO notes (user_id, topic_id, title, content, is_pinned)                                                                                                                                  
            VALUES ($1, $2, $3, $4, $5)                                                                                                                                                                       
            RETURNING id, topic_id, title, content, is_pinned, version, created_at`,                                                                                                                          
            [userId, topicId || null, title, content, isPinned]                                                                                                                                                
        );                                                                                                                                                                                                   
                                                                                                                                                                                                            
        return ApiResponse.success(res, 201, 'Tạo ghi chú thành công', result.rows[0]);                                                                                                                      
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Cập nhật Ghi chú thường (PUT /api/v1/notes/:id) - Có Optimistic Locking                                                                                                                            
    static async updateNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const userId = req.user?.userId;                                                                                                                                                                       
        const { id } = req.params;                                                                                                                                                                             
        const { topicId, title, content, isPinned, version } = req.body;                                                                                                                                       
                                                                                                                                                                                                                
        if (version === undefined) {                                                                                                                                                                           
            return ApiResponse.error(res, 400, 'BAD_REQUEST', 'Thiếu trường version để kiểm tra xung đột dữ liệu');                                                                                              
        }                                                                                                                                                                                                      
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            // Optimistic Locking Check: Chỉ update nếu version trong DB đúng bằng version client gửi lên                                                                                                        
            const result = await dbPool.query(                                                                                                                                                                   
                `UPDATE notes                                                                                                                                                                                      
                SET topic_id = $1, title = $2, content = $3, is_pinned = $4, version = version + 1, updated_at = CURRENT_TIMESTAMP                                                                                
                WHERE id = $5 AND user_id = $6 AND version = $7                                                                                                                                                   
                RETURNING id, title, content, version, updated_at`,                                                                                                                                               
                [topicId || null, title, content, isPinned, id, userId, version]                                                                                                                                   
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            if (result.rows.length === 0) {                                                                                                                                                                      
                return ApiResponse.error(                                                                                                                                                                          
                    res,                                                                                                                                                                                             
                    409,                                                                                                                                                                                             
                    'CONFLICT',                                                                                                                                                                                      
                    'Xung đột dữ liệu! Ghi chú này đã được sửa bởi một thiết bị khác. Vui lòng tải lại trang!'                                                                                                       
                );                                                                                                                                                                                                 
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Cập nhật ghi chú thành công', result.rows[0]);                                                                                                                 
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    // Xóa Ghi chú (DELETE /api/v1/notes/:id)                                                                                                                                                             
    static async deleteNote(req: AuthenticatedRequest, res: Response) {                                                                                                                                      
        const userId = req.user?.userId;                                                                                                                                                                       
        const { id } = req.params;                                                                                                                                                                             
                                                                                                                                                                                                                
        try {                                                                                                                                                                                                  
            const result = await dbPool.query(                                                                                                                                                                   
                'DELETE FROM notes WHERE id = $1 AND user_id = $2 RETURNING id',                                                                                                                                   
                [id, userId]                                                                                                                                                                                       
            );                                                                                                                                                                                                   
                                                                                                                                                                                                                
            if (result.rows.length === 0) {                                                                                                                                                                      
                return ApiResponse.error(res, 404, 'NOT_FOUND', 'Không tìm thấy ghi chú hoặc không có quyền xóa');                                                                                                 
            }                                                                                                                                                                                                    
                                                                                                                                                                                                                
            return ApiResponse.success(res, 200, 'Xóa ghi chú thành công');                                                                                                                                      
        } catch (error: any) {                                                                                                                                                                                 
            return ApiResponse.error(res, 500, 'INTERNAL_SERVER_ERROR', error.message);                                                                                                                          
        }                                                                                                                                                                                                      
    }                                                                                                                                                                                                        
}