import { Request, Response, NextFunction } from 'express';                                                                                                                                                 
import jwt from 'jsonwebtoken';                                                                                                                                                                            
import { config } from '../config/env';                                                                                                                                                                    
import { ApiResponse } from '../utils/response.util';                                                                                                                                                      
                                                                                                                                                                                                            
export interface AuthenticatedRequest extends Request {                                                                                                                                                    
    user?: {                                                                                                                                                                                                 
        userId: string;                                                                                                                                                                                        
        username: string;                                                                                                                                                                                      
    };                                                                                                                                                                                                       
}                                                                                                                                                                                                          
                                                                                                                                                                                                            
export const authenticateJWT = (req: AuthenticatedRequest, res: Response, next: NextFunction) => {                                                                                                         
    const authHeader = req.headers.authorization;                                                                                                                                                            
                                                                                                                                                                                                            
    if (!authHeader || !authHeader.startsWith('Bearer ')) {                                                                                                                                                  
        return ApiResponse.error(res, 401, 'UNAUTHORIZED', 'Thiếu JWT Token hoặc Format không đúng (Bearer <token>)');                                                                                         
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    const token = authHeader.split(' ')[1];                                                                                                                                                                  
                                                                                                                                                                                                            
    if (!token) {                                                                                                                                                                                            
        return ApiResponse.error(res, 401, 'UNAUTHORIZED', 'Token không được để rỗng');                                                                                                                        
    }                                                                                                                                                                                                        
                                                                                                                                                                                                            
    try {                                                                                                                                                                                                    
        const decoded = jwt.verify(token, config.SECURITY.JWT_SECRET) as { userId: string; username: string };                                                                                                 
        req.user = decoded; // Gán thông tin user vào Request object                                                                                                                                           
        next(); // Cho phép đi tiếp vào Controller                                                                                                                                                 
    } catch (error) {                                                                                                                                                                                        
        return ApiResponse.error(res, 401, 'UNAUTHORIZED', 'JWT Token đã hết hạn hoặc không hợp lệ');                                                                                                          
    }                                                                                                                                                                                                        
};